name: Add PR to Code Samples Changes project

on:
  pull_request_target:
    types: [opened, edited, synchronize]
    paths:
      - '.code-samples.meilisearch.yaml'

jobs:
  add-pr-to-project:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/add-to-project@5b1a254a3546aef88e0a7724a77a623fa2e47c36
        with:
          project-url: https://github.com/orgs/meilisearch/projects/44
          github-token: ${{ secrets.GH_TOKEN }}
